import Navbar from "@/components/Navbar";
import "./globals.css";
import SideBar from "@/components/SideBar";
import ReduxProvider from "./reduxProvider";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Impresiot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <ReduxProvider>
          <Navbar />
          <div className="w-[20rem]">
            <SideBar />
          </div>
          {children}
          <Footer/>
        </ReduxProvider>
        <Toaster/>
      </body>
    </html>
  );
}
